plugins {
	id 'java'
	id 'application'
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'com.google.code.gson:gson:2.11.0'
	implementation 'com.formdev:flatlaf:3.5.4'
	implementation 'net.java.dev.jna:jna:5.14.0'
	implementation 'net.java.dev.jna:jna-platform:5.14.0'
	implementation 'com.googlecode.soundlibs:vorbisspi:1.0.3.3'
	implementation 'com.googlecode.soundlibs:jorbis:0.0.17.4'
	implementation 'com.googlecode.soundlibs:tritonus-share:0.3.7.4'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

application {
	mainClass = 'willits.jhenry.controller.Main'
}
